
title: Ruben's Maker Log
email: ruben.podadera@gmail.com
description: |
  A blog about making things
baseurl: "/maker-log" # the subpath of your site, e.g. /blog
# url: "https://ruben-podadera.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

theme: jekyll-theme-hacker
